/**
 * Concatenate the design tokens into one stylesheet.
 *
 * The export chained them with @import, which the browser resolves serially:
 * styles.css must arrive before it learns tokens/colors.css exists, and so on
 * for nine files. Bundling them collapses that to a single request.
 *
 * tokens/fonts.css is skipped on purpose — it holds only Google Fonts @imports,
 * which the layout now issues as <link> tags so they download in parallel with
 * the CSS instead of waiting behind it.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const tokensDir = join(root, 'public', 'css', 'tokens')

// Order matters: later files override earlier ones (dark.css last).
const ORDER = [
  'colors.css',
  'typography.css',
  'spacing.css',
  'radii.css',
  'shadows.css',
  'motion.css',
  'base.css',
  'dark.css',
]

const parts = [
  '/* GENERATED by scripts/build-css.mjs — edit public/css/tokens/*.css instead. */',
]

for (const file of ORDER) {
  parts.push(`\n/* ── ${file} ─────────────────────────────────────── */`)
  parts.push(readFileSync(join(tokensDir, file), 'utf8').trimEnd())
}

const out = join(root, 'public', 'css', 'tokens.bundle.css')
const css = parts.join('\n') + '\n'
writeFileSync(out, css)

console.log(`build:css → public/css/tokens.bundle.css (${ORDER.length} files, ${(css.length / 1024).toFixed(1)} KB)`)
